--dim_x 20
--dim_y 20
--dim_z 20
--rank_n_x 1
--rank_n_y 1
--rank_n_z 1
--mean_growth_period 24
--mean_starvation_period 24
--branch_prob 0.2
--mean_cap_growth_period 24
--nutrient_rate 1.0
--gf_rate 0.1
--af_rate 0.01
--bmr 5e-04
--cost_of_res 5e-04
--diffusion_rate 0.001
--mutation_rate 0.01
--apoptosis_chance_per_mutation 0.01
--telomere_length 50
--time_steps 50000
--warmup_period 7000
--sample_period 1000